#Temp Data for Automation Test
#Mon Dec 22 18:44:32 JST 2025
PRODUCT_NAME_USER=Gi\u1ECF qu\u00E0 T\u1EBFt QbAIn
ORDER_CODE=20251222-16442992
QUANTITY_USER=1
PRODUCT_PRICE_USER=$5,000,000.00
PRODUCT_TOTAL_PRICE_USER=$5,030,000.00
